"""Bytecode generation for BASIC AST nodes."""

from dataclasses import dataclass, field
import json
from typing import Dict, List, Optional, Union

from .ast_nodes import (
    Assignment,
    BinaryExpression,
    Literal,
    PrintStatement,
    Program,
    VariableReference,
)


@dataclass(frozen=True)
class BytecodeInstruction:
    """Single bytecode instruction."""

    opcode: str
    operand: Optional[Union[int, str]] = None

    def to_dict(self) -> dict:
        data = {"opcode": self.opcode}
        if self.operand is not None:
            data["operand"] = self.operand
        return data


@dataclass
class BytecodeProgram:
    """Container for generated bytecode."""

    instructions: List[BytecodeInstruction] = field(default_factory=list)
    constants: List[Union[int, float, str]] = field(default_factory=list)

    def to_bytes(self) -> bytes:
        payload = {
            "constants": self.constants,
            "instructions": [instruction.to_dict() for instruction in self.instructions],
        }
        return json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


class BasicCodeGenerator:
    """Visits AST nodes to produce bytecode instructions."""

    def __init__(self) -> None:
        self.instructions: List[BytecodeInstruction] = []
        self.constants: List[Union[int, float, str]] = []
        self.constant_indices: Dict[Union[int, float, str], int] = {}

    def generate(self, program: Program) -> BytecodeProgram:
        for statement in program.statements:
            self._emit_statement(statement)
        return BytecodeProgram(self.instructions, self.constants)

    def _emit_statement(self, statement) -> None:
        if isinstance(statement, Assignment):
            self._emit_expression(statement.value)
            self.instructions.append(BytecodeInstruction("STORE_VAR", statement.name))
            return
        if isinstance(statement, PrintStatement):
            self._emit_expression(statement.value)
            self.instructions.append(BytecodeInstruction("PRINT"))
            return
        raise ValueError(f"Unsupported statement type: {type(statement).__name__}")

    def _emit_expression(self, expression) -> None:
        if isinstance(expression, Literal):
            constant_index = self._add_constant(expression.value)
            self.instructions.append(BytecodeInstruction("LOAD_CONST", constant_index))
            return
        if isinstance(expression, VariableReference):
            self.instructions.append(BytecodeInstruction("LOAD_VAR", expression.name))
            return
        if isinstance(expression, BinaryExpression):
            self._emit_expression(expression.left)
            self._emit_expression(expression.right)
            opcode = {
                "+": "BINARY_ADD",
                "-": "BINARY_SUB",
                "*": "BINARY_MUL",
                "/": "BINARY_DIV",
            }.get(expression.operator)
            if opcode is None:
                raise ValueError(f"Unsupported operator: {expression.operator}")
            self.instructions.append(BytecodeInstruction(opcode))
            return
        raise ValueError(f"Unsupported expression type: {type(expression).__name__}")

    def _add_constant(self, value: Union[int, float, str]) -> int:
        if value in self.constant_indices:
            return self.constant_indices[value]
        index = len(self.constants)
        self.constants.append(value)
        self.constant_indices[value] = index
        return index
